# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-drv-evdev
Summary:    Xorg X11 evdev input driver
Version:    2.6.0
Release:    0
Group:      System/X Hardware Support
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/releases/individual/driver/xf86-input-evdev-%{version}.tar.bz2
Source100:  xorg-x11-drv-evdev.yaml
Patch0:     xinput2-declare-left-button-label-for-touchscreens.patch
Requires:   xorg-x11-server-Xorg
BuildRequires:  pkgconfig(xorg-server)
BuildRequires:  pkgconfig(xkbfile)
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(inputproto)
BuildRequires:  pkgconfig(xrandr)
BuildRequires:  pkgconfig(randrproto)
BuildRequires:  pkgconfig(xextproto)


%description
The Xorg X11 evdev input driver


%package devel
Summary:    Development files for xorg evdev driver
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains xorg evdev development files


%prep
%setup -q -n xf86-input-evdev-%{version}

# xinput2-declare-left-button-label-for-touchscreens.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post









%files
%defattr(-,root,root,-)
# >> files
%(pkg-config xorg-server --variable=moduledir )/input/evdev_drv.so
%doc %{_mandir}/man4/evdev.4*
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/xorg/evdev-properties.h
%{_libdir}/pkgconfig/xorg-evdev.pc
# << files devel

